name: Deploy DynamoDB with SAM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Run CloudFormation Linter
        uses: scottbrenner/cfn-lint-action@v2
        with:
          command: cfn-lint -t template.yaml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubOIDCRole
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Deploy DynamoDB Table with SAM
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
