name: Deploy DynamoDB with SAM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      OIDC_ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubOIDCRole
      STACK_NAME: taskly-dynamodb
      S3_BUCKET: ${{ secrets.SAM_S3_BUCKET }}
      CFN_EXEC_ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/CloudFormationExecRole

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Run CloudFormation Linter
        uses: scottbrenner/cfn-lint-action@v2
        with:
          command: cfn-lint -t template.yaml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.OIDC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Deploy DynamoDB Table with SAM
        run: |
          sam deploy \
            --stack-name $STACK_NAME \
            --region $AWS_REGION \
            --s3-bucket $S3_BUCKET \
            --s3-prefix sam-artifacts \
            --capabilities CAPABILITY_NAMED_IAM \
            --role-arn $CFN_EXEC_ROLE \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
